/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#f472b6",
        "on-tertiary": "#ffffff",
        "surface-tint": "#6d28d9",
        "secondary-fixed": "#fce7f3",
        "tertiary-fixed": "#ccfbf1",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-container-high": "#e5e7eb",
        "on-primary-fixed": "#3c1053",
        "surface-dim": "#d1d5db",
        "on-error": "#ffffff",
        "inverse-on-surface": "#fafafa",
        "on-secondary-fixed": "#831843",
        "outline-variant": "#cbd5e1",
        "surface-variant": "#e2e8f0",
        "outline": "#64748b",
        "primary-fixed-dim": "#a78bfa",
        "inverse-surface": "#18181b",
        "secondary": "#ec4899",
        "tertiary-container": "#0f766e",
        "on-tertiary-fixed-variant": "#134e4a",
        "primary-fixed": "#ede9fe",
        "surface-container-low": "#ffffff",
        "primary": "#6d28d9",
        "on-secondary-container": "#fbcfe8",
        "on-secondary-fixed-variant": "#be185d",
        "background": "#f3f4f6",
        "surface-container": "#f8fafc",
        "on-surface-variant": "#475569",
        "error-container": "#ffdad6",
        "on-surface": "#0f172a",
        "on-secondary": "#ffffff",
        "tertiary": "#06b6d4",
        "surface-bright": "#f3f4f6",
        "on-tertiary-fixed": "#042f2e",
        "error": "#ba1a1a",
        "on-background": "#0f172a",
        "on-primary-container": "#c4b5fd",
        "primary-container": "#4c1d95",
        "surface": "#f3f4f6",
        "on-primary-fixed-variant": "#5b21b6",
        "tertiary-fixed-dim": "#22d3ee",
        "on-tertiary-container": "#cffafe",
        "inverse-primary": "#a78bfa",
        "surface-container-highest": "#f1f5f9",
        "secondary-container": "#db2777",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
